name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Stylua and Selene
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install Tools
        run: cargo install selene stylua --locked
      - name: Run Selene
        run: selene lua
      - name: Run Stylua
        run: stylua --check lua
